name: Run Maven Tests Manually for each class

on:
  workflow_dispatch:
    inputs:
      testClass:
        description: 'Test class to run (leave empty to run all)'
        required: false
        default: ''
      mavenProfile:
        description: 'Maven profile to use (leave empty for default)'
        required: false
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Run Maven tests
        run: |
          CMD="mvn clean test"
          if [ "${{ github.event.inputs.testClass }}" != "" ]; then
            CMD="$CMD -Dtest=${{ github.event.inputs.testClass }}"
          fi
          if [ "${{ github.event.inputs.mavenProfile }}" != "" ]; then
            CMD="$CMD -P${{ github.event.inputs.mavenProfile }}"
          fi
          echo "Running: $CMD"
          $CMD
